name: dasi
services:
  gateway:
    container_name: gateway-service
    build:
      context: ./gateway
      dockerfile: Dockerfile
    command: npm run start:prod
    ports:
      - 3000:3000
    volumes:
      - ./gateway:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - identity
      - analytics
      - rabbitmq
    networks:
      - dasi-net

  identity:
    container_name: identity-service
    build:
      context: ./identity
      dockerfile: Dockerfile
    command: npm run start:prod
    ports:
      - 3001:3001
    volumes:
      - ./identity:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres-identity
      - rabbitmq
    networks:
      - dasi-net

  
  postgres-identity:
    image: postgres:16-alpine
    container_name: postgres-identity
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: identity
      PGDATA: /var/lib/postgresql/data/pgdata 
    volumes:
      - postgres-identity-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - dasi-net
  

  analytics:
    container_name: analytics-service
    build:
      context: ./analytics
      dockerfile: Dockerfile
    command: npm run start:prod
    ports:
      - 3002:3002
    volumes:
      - ./analytics:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres-analytics
      - rabbitmq
    networks:
      - dasi-net

  postgres-analytics:
    image: postgres:16-alpine
    container_name: postgres-analytics
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: analytics
      PGDATA: /var/lib/postgresql/data/pgdata 
    volumes:
      - postgres-analytics-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - dasi-net

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - 5672:5672
    networks:
      - dasi-net

volumes:
  postgres-identity-data:
  postgres-analytics-data:
networks:
  dasi-net:
    driver: bridge